---
# .readthedocs.yaml — ReadTheDocs build configuration for CloudAudit
# https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

# Use MkDocs as the documentation framework
mkdocs:
  configuration: mkdocs.yml

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - gemini
        - openai
